<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\AgentRuntime\AgentRuntime.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Safety\Safety.csproj" />
    <ProjectReference Include="..\..\src\RuleEvaluator\RuleEvaluator.csproj" />
  </ItemGroup>

</Project>